DROP DATABASE IF EXISTS GALERIA_FOTOS;
CREATE DATABASE GALERIA_FOTOS;
USE GALERIA_FOTOS;


DROP TABLE IF EXISTS CATEGORIAS;
CREATE TABLE CATEGORIAS(
	IDE_CAT INT(2) PRIMARY KEY AUTO_INCREMENT,
    NOM_CAT VARCHAR(40) NOT NULL,
    DES_CAT VARCHAR(100)
);

DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS(
		IDE_USU INT(3) PRIMARY KEY AUTO_INCREMENT,
        NOM_USU VARCHAR(25) NOT NULL,
        EMA_USU VARCHAR(50) NOT NULL,
        TEL_USU VARCHAR(12),
		TIP_USU ENUM('USUA', 'ADMI'),
        CONT_USU VARCHAR(250) NOT NULL 
);

DROP TABLE IF EXISTS FOTOS;
CREATE TABLE FOTOS(
	IDE_FOT INT(5) PRIMARY KEY AUTO_INCREMENT,
    # Nombre fisico con la extesion
    NOM_FOT VARCHAR(100) NOT NULL,
    # Nombre que aparacera de la foto
    LEY_FOT VARCHAR(25), 
    
    FEC_FOT DATE NOT NULL,
    
    # Numero de likes
    LIK_FOT INT(7),
    
    # Si es publica o no
    PUB_FOT TINYINT DEFAULT 0,
    FK_IDE_CAT INT(2) NOT NULL,
    FK_IDE_USU INT(3) NOT NULL,
    CONSTRAINT REL_FOT_CAT FOREIGN KEY(FK_IDE_CAT) REFERENCES CATEGORIAS(IDE_CAT) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT REL_FOT_USU FOREIGN KEY(FK_IDE_USU) REFERENCES USUARIOS(IDE_USU) ON DELETE RESTRICT ON UPDATE RESTRICT
    
);

