DROP DATABASE IF EXISTS FACTURACION;
CREATE DATABASE FACTURACION;
USE FACTURACION;

DROP TABLE IF EXISTS CUENTAS;
CREATE TABLE CUENTAS(
		CUE_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
        CUE_RUC VARCHAR(13) NOT NULL, # CORRESPONDE A SU USUARIO
        CUE_PAS  VARCHAR(250) NOT NULL, # CONTRASEGNIA
        CUE_EST TINYINT NOT NULL, #ESTADO, ACTIVO O DESACTIVO
		CUE_FEC_REG DATE NOT NULL, #FECHA REGISTRO
        CUE_ROL VARCHAR(25) NOT NULL, # ROL
        CONSTRAINT UNIQUE_RUC_CUE  UNIQUE(CUE_RUC) # RESTRICCION PARA QUE NO EXISTAN RUC IGUALES
);

/*
Tabla emisores/remitentes
*/
DROP TABLE IF EXISTS EMISORES;
CREATE TABLE EMISORES(
				EMI_COD INTEGER PRIMARY KEY,
				EMI_RUC VARCHAR(15) NOT NULL,
                EMI_RAZ_SOC VARCHAR(250) NOT NULL, # RAZON SOCIAL/ NOMBRES APELLIDOS 
				EMI_NOM_COM VARCHAR(250), # NOMBRE COMERCIAL
				EMI_DIR_MAT VARCHAR(250), # DIRECCION ESTABLECIMIENTO MATRIZ
                EMI_COD_EST_EMI VARCHAR(3) NOT NULL, # CODIGO ESTABLECIMIENTO EMISOR
				EMI_DIR_EST VARCHAR(250), # DIRECCION ESTABLECIMIENTO EMISOR  
                EMI_COD_PTO_EMI	 VARCHAR(3) NOT NULL, #CODIGO PUNTO DE EMISION
				EMI_CON_ESP VARCHAR(5), # CONTRIBUYENTE ESPECIAL (NUMERO DE RESOLUCION)
				EMI_OBL_CON ENUM('SI', 'NO') NOT NULL , # OBLIGADO A LLEVAR CONTABILIDAD
                EMI_TIP ENUM('NATURAL', 'JURIDICA'), # TIPO DE PERSONA
				EMI_LOG VARCHAR(255), # LOGO 
                EMI_TIP_AMB VARCHAR(1) NOT NULL, # TIPO DE AMBIENTE
				EMI_TIP_EMI VARCHAR(1)NOT NULL, # TIPO DE EMISION
				EMI_REG_RIM TINYINT NOT NULL, # REGIMEN RIMPE
                EMI_PRO VARCHAR(2), #CODIGO DE LA PROVINCIA, ESTE ES NETAMENTE PARA EL SISTEMA
				CONSTRAINT UNIQUE_RUC  UNIQUE(EMI_RUC), # RESTRICCION PARA QUE NO EXISTAN DOS RUC IGUALES
				CONSTRAINT REL_EMI_CUE FOREIGN KEY(EMI_COD) REFERENCES CUENTAS(CUE_COD)
                );  
                
/*
	TABLE ESTABLECIMIENTOS
*/

DROP TABLE IF EXISTS ESTABLECIMIENTOS;
CREATE TABLE ESTABLECIMIENTOS(
    EST_COD VARCHAR(4) PRIMARY KEY NOT NULL, # CODIGO DE TRES DIGITOS DEL ESTABLECIMIENTO,  EJM:001
    EST_RAZ_SOC VARCHAR(250), # NOMBRE SUCURSAL, DEBERIA SER EL MISMO QUE EL PRINCIPAL
	EST_DIR VARCHAR(250), # DIRECCION  SUCURSAL
    EST_EST  CHAR(1), # ESTADO SUCURSAL
    EST_FEC DATE,  # FECHA REGISTRO ESTABLECIMIENTO
    EST_FK_COD_EMI INTEGER,
	CONSTRAINT REL_EST_EMI FOREIGN KEY(EST_FK_COD_EMI) REFERENCES EMISORES(EMI_COD)
);

/*
TABLE  PUNTO DE EMISION
*/

DROP TABLE IF EXISTS PUNTOS_EMISION;

CREATE TABLE PUNTOS_EMISION(
    /*
    El punto de emision debe ser unico dentro de cada establecimiento, por ende se debe valdiar
    si cada nuevo punto no existe en el establecimiento actual
    */
   PTE_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
    PTE_COD_EMI VARCHAR(4)  NOT NULL, # CODIGO DEL PUNTO DE EMISION
    PTE_EST CHAR(1) NOT NULL, # ESTADO DEL PUNTO EMISION
    PTE_FEC DATE,
    PTE_CLA VARCHAR(250), # CLAVE DEL PUNTO DE EMISION
    PTE_FK_COD_EST VARCHAR(4) NOT NULL,
     # PRIMARY KEY (PTE_COD_EMI, PTE_FK_COD_EST),
    CONSTRAINT UNIQUE_PTE_EST  UNIQUE(PTE_COD_EMI,PTE_FK_COD_EST), # RESTRICCION PARA QUE NO EXISTAN DOS CODIGO ESTABLECIMIENTOS Y PUNTO EMISION IGUALES
	CONSTRAINT REL_PTE_EST FOREIGN KEY(PTE_FK_COD_EST) REFERENCES  ESTABLECIMIENTOS(EST_COD)
    
);


/*
	TABLE EMPLEADOS
*/
DROP TABLE IF EXISTS  EMPLEADOS;
CREATE TABLE EMPLEADOS(
	EMP_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
    EMP_NOM VARCHAR(100) NOT NULL, # NOMBRE
    EMP_CED VARCHAR(15) NOT NULL, # CEDULA
    EMP_CEL VARCHAR(10), # CELULAR,
    EMP_ROL ENUM('ADMIN', 'USSER'),
    EMP_FK_COD_PTE INTEGER, # RELACION PUNTO EMSION
    CONSTRAINT UNIQUE_EMP  UNIQUE(COD_CED,COD_FK_COD_PTE),
    CONSTRAINT REL_EMP_PTE FOREIGN KEY(COD_FK_COD_PTE) REFERENCES  PUNTOS_EMISION(PTE_COD)
);

 DROP TABLE IF EXISTS PLANES;
 CREATE TABLE PLANES(
	PLA_COD  VARCHAR(2)  NOT NULL PRIMARY KEY, # CODIGO 
    PLA_DES  ENUM('MENSUAL', 'ANUAL') NOT NULL,  # NOMBRE/ DESCRIPCION
    PLA_VAL DECIMAL NOT NULL # VALOR
 ); 

DROP TABLE IF EXISTS CONTRA_PLANES;
CREATE TABLE CONTRA_PLANES(
	CTP_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
    CTP_FEC_INI DATE NOT NULL, #FECHA QUE SE CONTRART UN PLAN
    CTP_FEC_FIN DATE NOT NULL, # FECHA QUE SE TERMINA EL PLAN
    CTP_EST TINYINT NOT NULL, # ESTADO DEL PLAN CONTRATADO
    CTP_FK_COD_CUE INTEGER NOT NULL, # CLAVE FORANEA DE CUENTAS
    CTP_FK_COD_PLA VARCHAR(2) NOT NULL, # CLAVE FORANEA DE TIPO PLAN CONTRATADO
	CONSTRAINT REL_COP_CUE FOREIGN KEY(CTP_FK_COD_CUE) REFERENCES CUENTAS(CUE_COD),
    CONSTRAINT REL_COP_PLA FOREIGN KEY(CTP_FK_COD_PLA) REFERENCES PLANES(PLA_COD)
 );

 
 DROP TABLE IF EXISTS LOGINS;
 CREATE TABLE LOGINS(
		LOG_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
        LOG_FEC_ING DATETIME NOT NULL, #FECHA Y HORA DE INGRESO
        LOG_FEC_SAL DATETIME, #FECHA Y HORA DE SALIDA
        LOG_FK_COD_CUE INTEGER NOT NULL, # CAMPO RELACIONADO CON LA CUENTAS
        CONSTRAINT REL_LOG_CUE FOREIGN KEY(LOG_FK_COD_CUE) REFERENCES CUENTAS(CUE_COD)
 
 );
 
 
/*
TABLE PERSONAS
*/
DROP TABLE IF EXISTS PERSONAS;
CREATE TABLE PERSONAS(
	PER_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
    PER_TIP_IDT CHAR(1) NOT NULL, # TIPO DE IDENTIFICACION
	PER_NUM_IDT VARCHAR(15) NOT NULL, # NUMERO DE IDENTIFICACION
    PER_RAZ_SOC VARCHAR(70) NOT NULL, # RAZON SOCIAL
    PER_EMA VARCHAR(100),  # EMAIL
	# PER_FK_COD_EMI INTEGER NOT NULL, # RELACION CON EMISORES
    CONSTRAINT UNIQUE_RUC UNIQUE(PER_NUM_IDT)
	#CONSTRAINT REL_PER_EMI FOREIGN KEY(PER_FK_COD_EMI) REFERENCES EMISORES(EMI_COD)
);


/*
	TABLE DETALLE_PERSDNAS
    
    LOS EMISORES PODRAS TENER VARIOS PERSONAS(CLIENTES, TRANSPORTISTAS) Y LAS PERSONAS PODRAN PERTENECER
    A VARIOS EMISORES TAMBIE, POR ESO ESTA TABLA

*/

DROP TABLE IF EXISTS DETALLE_PERSONAS;
 CREATE TABLE DETALLE_PERSONAS(
	DEP_COD INTEGER PRIMARY KEY  AUTO_INCREMENT,
    DEP_FK_COD_EMI INTEGER,
    DEP_FK_COD_PER INTEGER,
    CONSTRAINT REL_DEP_EMI FOREIGN KEY(DEP_FK_COD_EMI) REFERENCES EMISORES(EMI_COD),
    CONSTRAINT REL_DEP_PER FOREIGN KEY(DEP_FK_COD_PER) REFERENCES PERSONAS(PER_COD)
 
 );



/*
TABLA : CLIENTES/DESTINATARIOS HEREDA DE PERSONAS
*/

DROP TABLE IF EXISTS CLIENTES;                
CREATE TABLE CLIENTES (
				CLI_PER INTEGER PRIMARY KEY, # CODIGO PERSONA
				CLI_DIR VARCHAR(250), # DIRECCION
				CLI_TLF_CON VARCHAR(15), # TELEFONO CONVENCIONAL
				CLI_EXT_TLF VARCHAR(3), # EXTESNSION TELEFONO CONVENCIONAL
				CLI_CEL VARCHAR(15), # CELULAR
				CLI_TIP VARCHAR(1) NOT NULL, # TIPO DE CLIENTE
                /*Se debe validar que tipo de cliente y numero de identificacion (ambos unidos) no se repitan*/
				CONSTRAINT REL_CLI_PER FOREIGN KEY(CLI_PER) REFERENCES PERSONAS(PER_COD)

);

/*
	TABLE TRANSPORTISTAS HEREDA DE PERSONAS
*/
DROP TABLE IF EXISTS TRANSPORTISTAS;
CREATE  TABLE TRANSPORTISTAS(
				TRA_PER INTEGER PRIMARY KEY, # CODIGO DE PERSONAS
				TRA_PLA VARCHAR(10) NOT NULL, #PLACA
                CONSTRAINT REL_TRA_PER FOREIGN KEY(TRA_PER) REFERENCES PERSONAS(PER_COD)
);


/*
	TABLE PRODUCTOS
*/
DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS(
				
                PRO_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
				PRO_COD_PRI VARCHAR(25) NOT NULL, # CODIGO PRINCIPAL
				PRO_COD_AUX VARCHAR(25), # CODIGO AUXILIAR
				PRO_TIP VARCHAR(1) NOT NULL, # TIPO PRODUCTO
                PRO_NOM VARCHAR(100) NOT NULL,  # NOMBRE/DESCRIPCION
				PRO_VAL_UNI DECIMAL NOT NULL, # VALOR UNITARIO
				PRO_IVA VARCHAR(1), # IVA
				PRO_ICE VARCHAR(1), #  ICE
				PRO_IRB CHAR(1), # IRBPNR
                PRO_FK_COD_EMI  INTEGER NOT NULL, #CLAVE FORANEA PARA ASOSCIAR UN PRODUCTO CON SU REMITENTE
				CONSTRAINT UNIQUE_COD_PRODUCTO UNIQUE(PRO_COD_PRI,PRO_COD_AUX, PRO_NOM),
                CONSTRAINT REL_PRO_EMI FOREIGN KEY(PRO_FK_COD_EMI) REFERENCES EMISORES(EMI_COD)
);
                                
/*
	TABLE INFORMACION ADICIONAL DE CADA PRODUCTO
*/

DROP TABLE IF EXISTS INFO_ADICIONAL;
CREATE TABLE INFO_ADICIONAL(
					INF_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
					INF_ATR VARCHAR(255), # NOMBRE ATRIBUTO
					INF_VAL VARCHAR(255), # VALOR DE ATRIBUTO
					INF_FK_COD_PRO INTEGER, # CODIGO PRODUCTO
                    CONSTRAINT INF_PRO FOREIGN KEY(INF_FK_COD_PRO) REFERENCES PRODUCTOS(PRO_COD)
);     
                    
                    
/*
TABLE IMPUESTOS:
IVA, RENTA, 
*/
DROP TABLE IF EXISTS IMPUESTOS;
CREATE  TABLE IMPUESTOS(
				IMP_COD INTEGER NOT NULL PRIMARY KEY,
				IMP_TAIM_DES_IMP VARCHAR(255),
				IMP_TAIM_ESTADO VARCHAR(1)
                );

/*
TABLE IMPUESTO_VALOR
*/
DROP TABLE IF EXISTS IMPUESTO_VALOR;
CREATE  TABLE IMPUESTO_VALOR(
				IMV_COD VARCHAR(255) NOT NULL PRIMARY KEY, # CODIGO
				IMV_FK_COD_IMP INTEGER, # CODIGO IMPUESTO
				IMV_POR DECIMAL, # PORCENTAJE
				IMV_POR_RET DECIMAL, # PORCENTAJE RETENCION
				IMV_TIP_IMP VARCHAR(1), # TIPO IMPUESTO
				IMV_DES VARCHAR(250), # DESCRIPCION
				IMV_FEC_INI DATE, # FECHA DE INICIO
				IMV_FEC_FIN DATE, # FECHA FIN
                IMV_CODIGO_ADM INTEGER, #CODIGO ADM
				IMV_MAR_POR_LIB CHAR(1), # MARCA PORCENTAJE LIBRE
				CONSTRAINT REL_IMV_IMP FOREIGN KEY(IMV_FK_COD_IMP) REFERENCES IMPUESTOS(IMP_COD)
                );
                
/*
TABLE PRODUCTO_IMPUESTO
*/                
DROP TABLE IF EXISTS PRODUCTO_IMPUESTO;
CREATE TABLE PRODUCTO_IMPUESTO(
				PDI_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
                PDI_FK_COD_PRO INTEGER, # CODIGO DEL PRODUCTO
				PDI_FK_COD_IMP_VAL VARCHAR(255), # CODIGO IMPUESTO VALOR
				CONSTRAINT REL_PRO_IMP_PRO FOREIGN KEY(PDI_FK_COD_PRO) REFERENCES PRODUCTOS(PRO_COD),
				CONSTRAINT REL_PRO_IMP_IMV FOREIGN KEY(PDI_FK_COD_IMP_VAL) REFERENCES IMPUESTO_VALOR(IMV_COD)
                );

 /*
 TABLE FORMAS_PAGO
 */
DROP TABLE IF EXISTS FORMAS_PAGO;
CREATE TABLE FORMAS_PAGO(
					-- FPG_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
                    FPG_COD_FOR_PAG VARCHAR(2) PRIMARY KEY, # CODIGO DE FORMA DE PAGO
					FPG_DES VARCHAR(100), # DESCRIPCION
					FPG_FEC_INI DATE, # FECHA INIICIO
					FPG_FEC_FIN DATE # FECHA FIN               
                    
                    ) ;


/*
TABLE DOCUMENTOS
*/
DROP TABLE IF EXISTS DOCUMENTOS;
CREATE TABLE  DOCUMENTOS(
	DOC_COD INTEGER PRIMARY KEY AUTO_INCREMENT,
    DOC_COD_TIP VARCHAR(2) NOT NULL, # CODIGO TIPO DOCUMENTO
    DOC_NUM_SECU VARCHAR(10) NOT NULL, # NUMERO SECUENCAIAL
    DOC_CLA_ACC VARCHAR(50) NOT NULL, #  CLAVE DE ACCESO
    DOC_NUM_AUT VARCHAR(50) NOT NULL, #  NUMERO DE AUTORIZACION
    DOC_FEC_AUT DATETIME, # FECHA AUTORIZACION
    DOC_FEC_EMI DATE, # FECHA DE EMISION
    DOC_TIP_EMI VARCHAR(2) NOT NULL, # TIPO DE EMISION
	DOC_FK_COD_PTE INTEGER NOT NULL, # RELACION CON PUNTO DE EMISION
    
    # DOC_FK_COD_EMI INTEGER NOT NULL, # RELACION CON EMISORES
     DOC_FK_COD_PER INTEGER, # RELACION CON PERSONAS/CLIENTE-TRANSPORTISTAS
    # DOC_FK_COD_FPG VARCHAR(2) NOT NULL, # RELACION FORMA DE PAGO
	# CONSTRAINT REL_DOC_EMI FOREIGN KEY(DOC_FK_COD_EMI) REFERENCES EMISORES(EMI_COD),
    CONSTRAINT REL_DOC_PTE FOREIGN KEY(DOC_FK_COD_PTE) REFERENCES PUNTOS_EMISION(PTE_COD),
    CONSTRAINT REL_DOC_PER FOREIGN KEY(DOC_FK_COD_PER) REFERENCES PERSONAS(PER_COD)
);

/*
	TABE FACTURAS HEREDA DE DOCUMENTOS
*/
DROP TABLE IF  EXISTS FACTURAS;
 CREATE TABLE FACTURAS(
	
    #FACTURAS Y  NOTA DE DÉBITO INCLUYEN FORMA DE PAGO
	
    FAC_DOC INTEGER PRIMARY KEY, # CODIGO DE DOCUMENTOS
    FAC_GUI_REM VARCHAR(15) NOT NULL,  # GUIA DE REMISION
    # FAC_COD_TIP_DOC VARCHAR(2) NOT NULL, # CODIGO TIPO DOCUMENTO
    # FAC_NUM_SECU VARCHAR(10) NOT NULL, # NUMERO SECUENCAIAL
    # FAC_CLA_ACC VARCHAR(50) NOT NULL, #  CLAVE DE ACCESO
    # FAC_NUM_AUT VARCHAR(50) NOT NULL, #  NUMERO DE AUTORIZACION
    #F AC_FEC_AUT DATETIME, # FECHA AUTORIZACION
    # FAC_FEC_EMI DATE, # FECHA DE EMISION
    # FAC_TIP_EMI VARCHAR(2) NOT NULL, # TIPO DE EMISION
    # FAC_FK_COD_EMI INTEGER NOT NULL, # RELACION CON EMISORES
	# FAC_FK_COD_PER INTEGER, # RELACION CON PERSONAS
     FAC_FK_COD_FPG VARCHAR(2) NOT NULL, # RELACION FORMA DE PAGO
	# CONSTRAINT REL_FAC_EMI FOREIGN KEY(FAC_FK_COD_EMI) REFERENCES EMISORES(EMI_COD),
    # CONSTRAINT REL_FAC_PER FOREIGN KEY(FAC_FK_COD_PER) REFERENCES PERSONAS(PER_COD),
	# CONSTRAINT REL_FAC_FPG FOREIGN KEY(FAC_FK_COD_FPG) REFERENCES FORMAS_PAGO(FPG_COD_FOR_PAG)
	CONSTRAINT REL_FAC_DOC FOREIGN KEY(FAC_DOC) REFERENCES DOCUMENTOS(DOC_COD),
    CONSTRAINT REL_FAC_FPG FOREIGN KEY(FAC_FK_COD_FPG) REFERENCES FORMAS_PAGO(FPG_COD_FOR_PAG)
 );
 

/*
TABLE DETALLE_FACTURA
*/

DROP TABLE IF EXISTS  FACTURA_VALORES;
CREATE TABLE FACTURA_VALORES(
	FVL_COD INTEGER PRIMARY KEY,
    FVL_SUB_IVA_ACT DECIMAL, # SUBTOTAL  APLICADO EL IVA ACTUAL / EN CASO APLIQUE
    FVL_SUB_IVA_CER DECIMAL, # SUBTOTAL IVA CERO
    FVL_SUB_NOT_OBJ_IVA DECIMAL , # SUBTOTAL NO OBJETO IVA
    FVL_SUB_EXE_IVA DECIMAL, # SUBTOTAL EXECTO IVA
    FVL_SUB DECIMAL, # SUBTOTAL
    FVL_DESC DECIMAL, # VALOR DESCUENTO
    FVL_ICE DECIMAL, # VALOR ICE
    FVL_RBP DECIMAL, # VALOR RBPNR
    FVL_IVA_ACT  DECIMAL, # VALOPR IVA
    FVL_PRO DECIMAL, # PROPINA
    FVL_TOT DECIMAL, # VALOR TOTAL
    CONSTRAINT REL_FVL_FAC FOREIGN KEY(FVL_COD) REFERENCES FACTURAS(FAC_DOC)
);

/*

TABLE DETALLE-FACTURAS
*/
DROP  TABLE IF EXISTS DETALLE_FACTURA;
CREATE TABLE DETALLE_FACTURA(
	DTF INTEGER PRIMARY KEY AUTO_INCREMENT,
    DTF_FK_COD_FAC  INTEGER, # RELACION CON LA FACTURA
    DTF_FK_COD_PRO INTEGER, # RELACION CON EL PRODUCTO/SERVICIO
    CONSTRAINT REL_DTF_FAC FOREIGN KEY(DTF_FK_COD_FAC) REFERENCES FACTURAS(FAC_DOC),
    CONSTRAINT REL_DTF_PRO FOREIGN KEY(DTF_FK_COD_PRO) REFERENCES PRODUCTOS(PRO_COD)
);



DROP TABLE IF EXISTS COMPENSACIONES;                    
CREATE  TABLE COMPENSACIONES(
					CODIGO_COMPENSACION INTEGER NOT NULL PRIMARY KEY,
					TARIFA_COMPENSACION INTEGER,
					CODIGO_PORCENTAJE_IVA INTEGER,
					TIPO_COMPENSACION VARCHAR(100),
					FECHA_INICIO DATE,
                    FECHA_FIN DATE
);
                    



/*

INSERCION DE DATOS ESTATICOS
*/

INSERT INTO IMPUESTOS VALUES(1,'RENTA','S');
INSERT INTO IMPUESTOS VALUES(2,'IVA','S');
INSERT INTO IMPUESTOS VALUES(3,'ICE','S');
INSERT INTO IMPUESTOS VALUES(5,'IRBPNR','S');

SELECT * FROM IMPUESTOS;



SELECT * FROM IMPUESTO_VALOR;

INSERT INTO IMPUESTO_VALOR VALUES('0',2,0,0,'I','0%','2009-07-04',NULL,0,'N');
INSERT INTO IMPUESTO_VALOR VALUES('1',2,0,30,'R','30%','2009-07-04',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('10000',2,0,100,'R','100% VALOR RETENIDO DISTRIBUIDOR','2014-06-30',NULL,5,'N');
INSERT INTO IMPUESTO_VALOR VALUES('10001',2,0,100,'R','100% VALOR RETENIDO VOCEADORES VARIOS','2014-06-30',NULL,6,'N');
INSERT INTO IMPUESTO_VALOR VALUES('10002',2,0,0,'R','0%','2015-06-01',NULL,7,'N');
INSERT INTO IMPUESTO_VALOR VALUES('10003',2,0,0,'R','0% NO PROCEDE RETENCION','2015-06-01',NULL,8,'N');
INSERT INTO IMPUESTO_VALOR VALUES('10004',2,0,10,'R','10%','2015-06-01',NULL,9,'N');
INSERT INTO IMPUESTO_VALOR VALUES('10005',2,0,20,'R','20%','2015-06-01',NULL,10,'N');
INSERT INTO IMPUESTO_VALOR VALUES('10006',2,0,100,'R','100%','2009-07-04',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('2',2,12,70,'I','12%','2009-07-04','2016-04-30',2,'S');
INSERT INTO IMPUESTO_VALOR VALUES('3',2,14,70,'I','14%','2016-06-01','2017-04-30',3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3011',3,10,0,'I','ICE  CIGARRILLOS RUBIOS','1996-07-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3021',3,10,0,'I','ICE  CIGARRILLOS NEGROS','1996-07-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3023',3,10,0,'I','ICE  PRODUCTOS DEL TABACO Y SUCED\u00c3\ufffdNEOS DEL TABACO EXCEPTO CIGARRILLOS','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('303',1,10,NULL,'R','HONORARIOS PROFESIONALES Y DEMAS PAGOS POR SERVICIOS RELACIONADOS CON EL TITULO PROFESIONAL','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3031',3,10,0,'I','ICE  BEBIDAS ALCOH\u00c3\u201cLICAS','1987-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3033',3,10,0,'I','ICE \u00e2\u20ac\u201c ALCOHOL','2018-04-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('304',1,8,NULL,'R','SERVICIOS PREDOMINA EL INTELECTO NO RELACIONADOS CON EL TITULO PROFESIONAL','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3041',3,10,0,'I','ICE  CERVEZA INDUSTRIAL','1996-07-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3043',3,10,0,'I','ICE  CERVEZA ARTESANAL','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('304A',1,8,NULL,'R','COMISIONES Y DEMAS PAGOS POR SERVICIOS PREDOMINA INTELECTO NO RELACIONADOS CON EL TITULO PROFESIONAL','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('304B',1,8,NULL,'R','PAGOS A NOTARIOS Y REGISTRADORES DE LA PROPIEDAD Y MERCANTIL POR SUS ACTIVIDADES EJERCIDAS COMO TALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('304C',1,8,NULL,'R','PAGOS A DEPORTISTAS, ENTRENADORES, ARBITROS, MIEMBROS DEL CUERPO TECNICO POR SUS ACTIVIDADES EJERCIDAS COMO TALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('304D',1,8,NULL,'R','PAGOS A ARTISTAS POR SUS ACTIVIDADES EJERCIDAS COMO TALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('304E',1,8,NULL,'R','HONORARIOS Y DEMAS PAGOS POR SERVICIOS DE DOCENCIA','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3053',3,10,0,'I','ICE  BEBIDAS GASEOSAS CON ALTO CONTENIDO DE AZ\u00c3\u0161CAR','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3054',3,10,0,'I','ICE  BEBIDAS GASEOSAS CON BAJO CONTENIDO DE AZ\u00c3\u0161CAR','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('307',1,2,NULL,'R','SERVICIOS PREDOMINA LA MANO DE OBRA','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3072',3,10,0,'I','ICE  CAMIONETAS Y FURGONES CUYO PVP SEA HASTA DE 30000 USD','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3073',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SEA HASTA DE 20000 USD','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3074',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS EXCEPTO CAMIONETAS Y FURGONETAS ENTRE 20000 y 30000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3075',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS PVP ENTRE 30000 Y 40000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3076',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SEA SUPERIOR A 40000 USD','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3077',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 40000 HASTA 50000','2008-08-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3078',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 50000 HASTA 60000','2008-08-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3079',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 60000 HASTA 70000','2008-08-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('308',1,10,NULL,'R','UTILIZACION O APROVECHAMIENTO DE LA IMAGEN O RENOMBRE','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3080',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 70000','2008-08-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3081',3,10,0,'I','ICE  AVIONES, TRICARES, YATES, BARCOS DE RECREO','1997-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('309',1,1,NULL,'R','SERVICIOS PRESTADOS POR MEDIOS DE COMUNICACION Y AGENCIAS DE PUBLICIDAD','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3092',3,10,0,'I','ICE  SERVICIOS DE TELEVISI\u00c3\u201cN PREPAGADA','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3093',3,10,0,'I','ICE  SERVICIOS TELEFON\u00c3\ufffdA','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('310',1,1,NULL,'R','SERVICIO DE TRANSPORTE PRIVADO DE PASAJEROS O TRANSPORTE PUBLICO O PRIVADO DE CARGA','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3101',3,10,0,'I','ICE  BEBIDAS ENERGIZANTES','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('311',1,2,NULL,'R','POR PAGOS A TRAVES DE LIQUIDACION DE COMPRA (NIVEL CULTURAL O RUSTICIDAD)','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3111',3,10,0,'I','ICE  BEBIDAS NO ALCOH\u00c3\u201cLICAS','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('312',1,1,NULL,'R','TRANSFERENCIA DE BIENES MUEBLES DE NATURALEZA CORPORAL','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('312A',1,1,NULL,'R','COMPRA DE BIENES DE ORIGEN AGRICOLA, AVICOLA, PECUARIO, APICOLA, CUNICULA, BIOACUATICO, Y FORESTAL','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('314A',1,8,NULL,'R','REGALIAS POR CONCEPTO DE FRANQUICIAS DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL - PAGO A PERSONAS NATURALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('314B',1,8,NULL,'R','CANONES, DERECHOS DE AUTOR, MARCAS, PATENTES Y SIMILARES DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL  PAGO A PERSONAS NATURALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('314C',1,8,NULL,'R','REGALIAS POR CONCEPTO DE FRANQUICIAS DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL - PAGO A SOCIEDADES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('314D',1,8,NULL,'R','CANONES, DERECHOS DE AUTOR,MARCAS, PATENTES Y SIMILARES DE ACUERDO A LEY DE PROPIEDAD INTELECTUAL  PAGO A SOCIEDADES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3171',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP SEA DE HASTA USD. 35.000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3172',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 35.000 HASTA USD 40.000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3173',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 40.000 HASTA USD 50.000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3174',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 50.000 HASTA USD 60.000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3175',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 60.000 HASTA USD 70.000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3176',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 70.000','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('319',1,1,NULL,'R','CUOTAS DE ARRENDAMIENTO MERCANTIL, INCLUSIVE LA DE OPCION DE COMPRA','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('320',1,8,NULL,'R','POR ARRENDAMIENTO BIENES INMUEBLES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('322',1,1,NULL,'R','SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323',1,2,NULL,'R','POR RENDIMIENTOS FINANCIEROS PAGADOS A NATURALES Y SOCIEDADES  (NO A IFIS)','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323A',1,2,NULL,'R','POR RF: DEPOSITOS CTA. CORRIENTE','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323B1',1,2,NULL,'R','POR RF:  DEPOSITOS CTA. AHORROS SOCIEDADES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323E',1,2,NULL,'R','POR RF: DEPOSITO A PLAZO FIJO GRAVADOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323E2',1,2,NULL,'R','POR RF: DEPOSITO A PLAZO FIJO EXENTOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('323F',1,2,NULL,'R','POR RENDIMIENTOS FINANCIEROS: OPERACIONES DE REPORTO - REPOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323G',1,2,NULL,'R','POR RF: INVERSIONES (CAPTACIONES) RENDIMIENTOS DISTINTOS DE AQUELLOS PAGADOS A IFIS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323H',1,2,NULL,'R','POR RF: OBLIGACIONES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323I',1,2,NULL,'R','POR RF: BONOS CONVERTIBLE EN ACCIONES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323M',1,2,NULL,'R','POR RF: INVERSIONES EN TITULOS VALORES EN RENTA FIJA GRAVADOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323N',1,2,NULL,'R','POR RF: INVERSIONES EN TITULOS VALORES EN RENTA FIJA EXENTOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('323O',1,2,NULL,'R','POR RF: INTERESES PAGADOS A BANCOS Y OTRAS ENTIDADES SOMETIDAS AL CONTROL DE LA SUPERINTENDENCIA DE BANCOS Y DE LA EPS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('323P',1,2,NULL,'R','POR RF: INTERESES PAGADOS POR ENTIDADES DEL SECTOR PUBLICO A FAVOR DE SUJETOS PASIVOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323Q',1,2,NULL,'R','POR RF: OTROS INTERESES Y RENDIMIENTOS FINANCIEROS GRAVADOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('323R',1,2,NULL,'R','POR RF: OTROS INTERESES Y RENDIMIENTOS FINANCIEROS EXENTOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('324A',1,1,NULL,'R','POR RF: INTERESES EN OPERACIONES DE CREDITO ENTRE INSTITUCIONES DEL SISTEMA FINANCIERO Y ENTIDADES ECONOMIA POPULAR Y SOLIDARIA.','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('324B',1,1,NULL,'R','POR RF: POR INVERSIONES ENTRE INSTITUCIONES DEL SISTEMA FINANCIERO Y ENTIDADES ECONOMIA POPULAR Y SOLIDARIA.','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('325',1,22,NULL,'R','ANTICIPO DIVIDENDOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('325A',1,22,NULL,'R','DIVIDENDOS ANTICIPADOS PRESTAMOS ACCIONISTAS, BENEFICIARIOS O PARTICIPES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('326',1,0,NULL,'R','DIVIDENDOS DISTRIBUIDOS QUE CORRESPONDAN AL IMPUESTO A LA RENTA UNICO ESTABLECIDO EN EL ART. 27 DE LA LRTI','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('327',1,0,NULL,'R','DIVIDENDOS DISTRIBUIDOS A PERSONAS NATURALES RESIDENTES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('328',1,0,NULL,'R','DIVIDENDOS DISTRIBUIDOS A SOCIEDADES RESIDENTES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('329',1,0,NULL,'R','DIVIDENDOS DISTRIBUIDOS A FIDEICOMISOS RESIDENTES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('330',1,0,NULL,'R','DIVIDENDOS GRAVADOS DISTRIBUIDOS EN ACCIONES (REINVERSION DE UTILIDADES SIN DERECHO A REDUCCION TARIFA IR)','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('331',1,0,NULL,'R','DIVIDENDOS EXENTOS DISTRIBUIDOS EN ACCIONES (REINVERSION DE UTILIDADES CON DERECHO A REDUCCION TARIFA IR)','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332',1,0,NULL,'R','OTRAS COMPRAS DE BIENES Y SERVICIOS NO SUJETAS A RETENCION','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332A',1,0,NULL,'R','POR LA ENAJENACION OCASIONAL DE ACCIONES O PARTICIPACIONES Y TITULOS VALORES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332B',1,0,NULL,'R','COMPRA DE BIENES INMUEBLES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332C',1,0,NULL,'R','TRANSPORTE PUBLICO DE PASAJEROS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332D',1,0,NULL,'R','PAGOS EN EL PAIS POR TRANS. DE PASAJ O TRANS. INTERN. DE CARGA, A CIAS NACIONALES O EXTRANJERAS DE AVIACION O MARITIMAS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332E',1,0,NULL,'R','VALORES ENTREGADOS POR LAS COOPERATIVAS DE TRANSPORTE A SUS SOCIOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332F',1,0,NULL,'R','COMPRAVENTA DE DIVISAS DISTINTAS AL DOLAR DE LOS ESTADOS UNIDOS DE AMERICA','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332G',1,0,NULL,'R','PAGOS CON TARJETA DE CREDITO','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332H',1,0,NULL,'R','PAGO AL EXTERIOR TARJETA DE CREDITO REPORTADA POR LA EMISORA DE TARJETA DE CREDITO, SOLO RECAP','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('332I',1,0,NULL,'R','PAGO A TRAVES DE CONVENIO DE DEBITO (CLIENTES IFIS)','2016-05-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('333',1,0.2,NULL,'R','ENAJENACION DE DERECHOS REPRESENTATIVOS DE CAPITAL Y OTROS DERECHOS COTIZADOS EN BOLSA ECUATORIANA','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('334',1,1,NULL,'R','ENAJENACION DE DERECHOS REPRESENTATIVOS DE CAPITAL Y OTROS DERECHOS NO COTIZADOS EN BOLSA ECUATORIANA','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('335',1,15,NULL,'R','POR LOTERIAS, RIFAS, APUESTAS Y SIMILARES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('336',1,0.2,NULL,'R','POR VENTA DE COMBUSTIBLES A COMERCIALIZADORAS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('337',1,0.3,NULL,'R','POR VENTA DE COMBUSTIBLES A DISTRIBUIDORES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('338',1,0,NULL,'R','COMPRA LOCAL DE BANANO A PRODUCTOR','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('339',1,0,NULL,'R','LIQUIDACION IMPUESTO UNICO A LA VENTA LOCAL DE BANANO DE PRODUCCION PROPIA','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('340',1,0,NULL,'R','IMPUESTO UNICO A LA EXPORTACION DE BANANO DE PRODUCCION PROPIA - COMPONENTE 1','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('341',1,0,NULL,'R','IMPUESTO UNICO A LA EXPORTACION DE BANANO DE PRODUCCION PROPIA - COMPONENTE 2','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('342',1,0,NULL,'R','IMPUESTO UNICO A LA EXPORTACION DE BANANO PRODUCIDO POR TERCEROS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('342A',1,0,NULL,'R','IMPUESTO UNICO A LA EXPORTACION DE BANANO PRODUCIDO POR TERCEROS DE ASOCIACIONES DE MICRO Y PEQUENOS PRODUCTORES HASTA 1000 CAJAS POR SEMANA POR CADA SOCIO','2016-05-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('342B',1,0,NULL,'R','IMPUESTO UNICO A LA EXPORTACION DE BANANO PODUCIDO POR TERCEROS DE ASOCIACIONES DE MICRO, PEQUENOS Y MEDIANOS PRODUCTORES','2016-05-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('343A',1,1,NULL,'R','POR ENERGIA ELECTRICA','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('343B',1,1,NULL,'R','POR ACTIVIDADES DE CONSTRUCCION DE OBRA MATERIAL INMUEBLE, URBANIZACION, LOTIZACION O ACTIVIDADES SIMILARES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('344',1,2,NULL,'R','OTRAS RETENCIONES APLICABLES EL 2%','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('344A',1,2,NULL,'R','PAGO LOCAL TARJETA DE CREDITO REPORTADA POR LA EMISORA DE TARJETA DE CREDITO, SOLO RECAP','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('346A',1,0,NULL,'R','GANANCIAS DE CAPITAL','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('347',1,0,NULL,'R','DONACIONES EN DINERO - IMPUESTO A LAS DONACIONES','2016-05-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('348',1,0,NULL,'R','RETENCION A CARGO DEL PROPIO SUJETO PASIVO POR LA EXPORTACION DE CONCENTRADOS Y/O ELEMENTOS METALICOS','2016-05-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('349',1,0,NULL,'R','RETENCION A CARGO DEL PROPIO SUJETO PASIVO POR LA COMERCIALIZACION DE PRODUCTOS FORESTALES','2016-05-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('3531',3,10,0,'I','ICE  IMPOR. ALCOHOL Y BEBIDAS ALCOH\u00c3\u201cLICAS DISTINTAS A LA CERVEZA CAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3532',3,10,0,'I','ICE \u00e2\u20ac\u201c IMPOR. ALCOHOL SENAE','2018-04-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3533',3,10,0,'I','ICE \u00e2\u20ac\u201c IMPOR. BEBIDAS ALCOH\u00c3\u201cLICAS SENAE','2018-04-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3541',3,10,0,'I','ICE  CERVEZA INDUSTRIAL','1996-07-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3542',3,10,0,'I','ICE  CIGARRILLOS RUBIOS - SENAE','2009-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3543',3,10,0,'I','ICE  CIGARRILLOS NEGROS - SENAE','2009-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3544',3,10,0,'I','ICE  PRODUCTOS DEL TABACO Y SUCED\u00c3\ufffdNEOS DEL TABACO EXCEPTO CIGARRILLOS - CAE','2009-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3545',3,10,0,'I','ICE  CERVEZA ARTESANAL - SENAE','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3552',3,10,0,'I','ICE  BEBIDAS GASEOSAS CON ALTO CONTENIDO DE AZ\u00c3\u0161CAR - SENAE','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3553',3,10,0,'I','ICE  BEBIDAS GASEOSAS CON BAJO CONTENIDO DE AZ\u00c3\u0161CAR - SENAE','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3581',3,10,0,'I','ICE  AERONAVES CAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3582',3,10,0,'I','ICE  AVIONES, AVIONETAS Y HELICOPTEROS EXCT. AQUELLOS DESTINADOS AL TRANS. CAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3601',3,10,0,'I','ICE  BEBIDAS ENERGIZANTES - SENAE','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3602',3,10,0,'I','ICE  BEBIDAS NO ALCOH\u00c3\u201cLICAS - SENAE','2016-05-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3610',3,10,0,'I','ICE  PERFUMES Y AGUAS DE TOCADOR','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3620',3,10,0,'I','ICE  VIDEOJUEGOS','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3630',3,10,0,'I','ICE  ARMAS DE FUEGO, ARMAS DEPORTIVAS Y MUNICIONES','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3640',3,10,0,'I','ICE  FOCOS INCANDESCENTES','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3650',3,10,0,'I','ICE  SERVICIOS DE CASINOS, SALAS DE JUEGO Y OTROS JUEGOS DE AZAR','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3660',3,10,0,'I','ICE  CUOTAS, MEMBREC\u00c3\ufffdAS, AFILIACIONES, ACCIONES','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3670',3,10,0,'I','ICE  COCINAS, COCINETAS, CALEFONES, A GAS.','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3671',3,10,0,'I','ICE \u00e2\u20ac\u201c CALEFONES Y SISTEMAS DE CALENTAMIENTO DE AGUA A GAS SRI','2018-09-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3680',3,10,0,'I','ICE FUNDAS PLASTICAS','2020-05-09',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3681',3,10,0,'I','ICE SERVICIOS DE TELEFONIA MOVIL PERSONAS NATURALES','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3682',3,10,0,'I','ICE CONSUMIBLES TABACO CALENTADO Y LIQUIDOS CON NICOTINA SRI','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3683',3,10,0,'I','ICE CONSUMIBLES TABACO CALENTADO Y LIQUIDOS CON NICOTINA SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3684',3,10,0,'I','ICE VEHICULOS MOTORIZADOS CAMIONETAS Y DE RESCATE CUYO PVP SEA HASTA DE 30000 USD','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3685',3,10,0,'I','ICE VEHICULOS MOTORIZADOS CAMIONETAS Y DE RESCATE PVP SEA HASTA DE 30000 USD SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3686',3,10,0,'I','ICE VEHICULOS MOTORIZADOS EXCEPTO CAMIONETAS Y DE RESCATE CUYO PVP SEA SUPERIOR USD 20000 HASTA DE 30000','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3687',3,10,0,'I','ICE VEHICULOS MOTORIZADOS EXCEPTO CAMIONETAS Y DE RESCATE CUYO PVP SEA SUPERIOR USD 20000 HASTA DE 30000 SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3688',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SEA DE HASTA USD 35000','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3689',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SEA DE HASTA USD 35000 SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3690',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 35000 HASTA 40000 SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3691',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 35000 HASTA 40000','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3692',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 40000 HASTA 50000','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3693',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 40000 HASTA 50000 SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3694',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 50000 HASTA 60000 SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3695',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 50000 HASTA 60000','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3696',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 60000 HASTA 70000','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3697',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR USD 60000 HASTA 70000 SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3698',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR A USD 70000','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3699',3,10,0,'I','ICE VEHICULOS HIBRIDOS CUYO PVP SUPERIOR A USD 70000 SENAE','2020-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3710',3,10,0,'I','ICE  PERFUMES AGUAS DE TOCADOR - CAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3720',3,10,0,'I','ICE  VIDEO JUEGOS - CAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3730',3,10,0,'I','ICE  IMPORTACIONES ARMAS DE FUEGO, ARMAS DEPORTIVAS Y MUNICIONES - CAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3740',3,10,0,'I','ICE  FOCOS INCANDESCENTES - CAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3770',3,10,0,'I','ICE  COCINAS, COCINETAS, CALEFONES, A GAS. IMPORTADAS.','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3771',3,10,0,'I','ICE \u00e2\u20ac\u201c CALEFONES Y SISTEMAS DE CALENTAMIENTO DE AGUA A GAS SENAE','2018-09-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3870',3,10,0,'I','ICE  CAMIONETAS Y FURGONES CUYO PVP SEA HASTA DE 30000 USD SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3871',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SEA HASTA DE 20000 USD - SENAE','2015-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3872',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS EXCEPTO CAMIONETAS Y FURGONETAS ENTRE 20000 Y 30000 SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3873',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS PVP ENTRE 30000 Y 40000 - SENAE','2015-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3874',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 40000 HASTA 50000 - SENAE','2015-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3875',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 50000 HASTA 60000 - SENAE','2015-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3876',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 60000 HASTA 70000 - SENAE','2015-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3877',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS MOTORIZADOS CUYO PVP SUPERIOR USD 70000 - SENAE','2015-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3878',3,10,0,'I','ICE  AVIONES, TRICARES, YATES, BARCOS DE RECREO - SENAE','2015-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3880',3,10,0,'I','ICE  VEH\u00c3\ufffdCULOS H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP SEA DE HASTA USD. 35.000 SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3881',3,10,0,'I','ICE  VEHIC H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 35.000 HASTA USD 40.000 SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3882',3,10,0,'I','ICE  VEHIC H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 40.000\u00c2\u00a0HASTA USD 50.000 SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3883',3,10,0,'I','ICE  VEHIC H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 50.000\u00c2\u00a0HASTA USD 60.000 SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3884',3,10,0,'I','ICE  VEHIC H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 60.000\u00c2\u00a0HASTA USD 70.000 SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('3885',3,10,0,'I','ICE  VEHIC H\u00c3\ufffdBRIDOS O EL\u00c3\u2030CTRICOS CUYO PVP MAYOR A USD. 70.000 SENAE','2008-01-01',NULL,3,'N');
INSERT INTO IMPUESTO_VALOR VALUES('500',1,0,NULL,'R','PAGO AL EXTERIOR - RENTAS INMOBILIARIAS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('5001',5,0,0,'B','BOTELLAS PLASTICAS NO RETORNABLES','2014-06-30',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('501',1,0,NULL,'R','PAGO AL EXTERIOR - BENEFICIOS EMPRESARIALES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('502',1,0,NULL,'R','PAGO AL EXTERIOR - SERVICIOS EMPRESARIALES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('503',1,0,NULL,'R','PAGO AL EXTERIOR - NAVEGACION MARITIMA Y/O AEREA','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('504',1,0,NULL,'R','PAGO AL EXTERIOR- DIVIDENDOS DISTRIBUIDOS A PERSONAS NATURALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('504A',1,0,NULL,'R','PAGO AL EXTERIOR - DIVIDENDOS A SOCIEDADES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('504B',1,22,NULL,'R','PAGO AL EXTERIOR - ANTICIPO DIVIDENDOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('504C',1,22,NULL,'R','PAGO AL EXTERIOR - DIVIDENDOS ANTICIPADOS PRESTAMOS ACCIONISTAS, BENEFICIARIOS O PARTICIPES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('504D',1,0,NULL,'R','PAGO AL EXTERIOR - DIVIDENDOS A FIDEICOMISOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('504E',1,0,NULL,'R','PAGO AL EXTERIOR- DIVIDENDOS DISTRIBUIDOS A PERSONAS NATURALES (PARAISOS FISCALES)','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('504F',1,13,NULL,'R','PAGO AL EXTERIOR - DIVIDENDOS A SOCIEDADES  (PARAISOS FISCALES)','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('504G',1,25,NULL,'R','PAGO AL EXTERIOR - ANTICIPO DIVIDENDOS  (PARAISOS FISCALES)','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('504H',1,13,NULL,'R','PAGO AL EXTERIOR - DIVIDENDOS A FIDEICOMISOS  (PARAISOS FISCALES)','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('505',1,0,NULL,'R','PAGO AL EXTERIOR - RENDIMIENTOS FINANCIEROS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('505A',1,0,NULL,'R','PAGO AL EXTERIOR: INTERESES DE CREDITOS DE INSTITUCIONES FINANCIERAS DEL EXTERIOR','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('505B',1,0,NULL,'R','PAGO AL EXTERIOR:INTERESES DE CREDITOS DE GOBIERNO A GOBIERNO','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('505C',1,0,NULL,'R','PAGO AL EXTERIOR:INTERESES DE CREDITOS DE ORGANISMOS MULTILATERALES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('505D',1,0,NULL,'R','PAGO AL EXTERIOR - INTERESES POR FINANCIAMIENTO DE PROVEEDORES EXTERNOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('505E',1,0,NULL,'R','PAGO AL EXTERIOR - INTERESES DE OTROS CREDITOS EXTERNOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('505F',1,0,NULL,'R','PAGO AL EXTERIOR - OTROS INTERESES Y RENDIMIENTOS FINANCIEROS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('509',1,0,NULL,'R','PAGO AL EXTERIOR - CANONES, DERECHOS DE AUTOR,  MARCAS, PATENTES Y SIMILARES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('509A',1,0,NULL,'R','PAGO AL EXTERIOR - REGALIAS POR CONCEPTO DE FRANQUICIAS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('510',1,0,NULL,'R','PAGO AL EXTERIOR - GANANCIAS DE CAPITAL','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('511',1,0,NULL,'R','PAGO AL EXTERIOR - SERVICIOS PROFESIONALES INDEPENDIENTES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('512',1,0,NULL,'R','PAGO AL EXTERIOR - SERVICIOS PROFESIONALES DEPENDIENTES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('513',1,0,NULL,'R','PAGO AL EXTERIOR - ARTISTAS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('513A',1,0,NULL,'R','PAGO AL EXTERIOR - DEPORTISTAS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('514',1,0,NULL,'R','PAGO AL EXTERIOR - PARTICIPACION DE CONSEJEROS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('515',1,0,NULL,'R','PAGO AL EXTERIOR - ENTRETENIMIENTO PUBLICO','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('516',1,0,NULL,'R','PAGO AL EXTERIOR - PENSIONES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('517',1,0,NULL,'R','PAGO AL EXTERIOR - REEMBOLSO DE GASTOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('518',1,0,NULL,'R','PAGO AL EXTERIOR - FUNCIONES PUBLICAS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('519',1,0,NULL,'R','PAGO AL EXTERIOR - ESTUDIANTES','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('520',1,0,NULL,'R','PAGO AL EXTERIOR - OTROS CONCEPTOS DE INGRESOS GRAVADOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('520A',1,0,NULL,'R','PAGO AL EXTERIOR - OTROS CONCEPTOS DE INGRESOS GRAVADOS','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('520B',1,0,NULL,'R','PAGO AL EXTERIOR - ARRENDAMIENTOS MERCANTIL INTERNACIONAL','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('520D',1,0,NULL,'R','PAGO AL EXTERIOR - COMISIONES POR EXPORTACIONES Y POR PROMOCION DE TURISMO RECEPTIVO','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('520E',1,0,NULL,'R','PAGO AL EXTERIOR - POR LAS EMPRESAS DE TRANSPORTE MARITIMO O AEREO Y POR EMPRESAS PESQUERAS DE ALTA MAR, POR SU ACTIVIDAD.','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('520F',1,0,NULL,'R','PAGO AL EXTERIOR - POR LAS AGENCIAS INTERNACIONALES DE PRENSA','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('520G',1,0,NULL,'R','PAGO AL EXTERIOR - CONTRATOS DE FLETAMENTO DE NAVES PARA EMPRESAS DE TRANSPORTE AEREO O MARITIMO INTERNACIONAL','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('521',1,5,NULL,'R','PAGO AL EXTERIOR - ENAJENACION DE DERECHOS REPRESENTATIVOS DE CAPITAL Y OTROS DERECHOS','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('522A',1,0,NULL,'R','PAGO AL EXTERIOR - SERVICIOS TECNICOS, ADMINISTRATIVOS O DE CONSULTORIA Y REGALIAS CON CONVENIO DE DOBLE TRIBUTACION','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('522B',1,22,NULL,'R','PAGO AL EXTERIOR - SERVICIOS TECNICOS, ADMINISTRATIVOS O DE CONSULTORIA Y REGALIAS SIN CONVENIO DE DOBLE TRIBUTACION','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('522C',1,35,NULL,'R','PAGO AL EXTERIOR - SERVICIOS TECNICOS, ADMINISTRATIVOS O DE CONSULTORIA Y REGALIAS EN PARAISOS FISCALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('523A',1,0,NULL,'R','PAGO AL EXTERIOR - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES)  CON CONVENIO DE DOBLE TRIBUTACION','2015-03-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('523B',1,22,NULL,'R','PAGO AL EXTERIOR - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES) SIN CONVENIO DE DOBLE TRIBUTACION','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('523C',1,35,NULL,'R','PAGO AL EXTERIOR - SEGUROS Y REASEGUROS (PRIMAS Y CESIONES) EN PARAISOS FISCALES','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('524',1,0,NULL,'R','PAGO AL EXTERIOR - OTROS PAGOS AL EXTERIOR NO SUJETOS A RETENCION','2015-03-01',NULL,1,'N');
INSERT INTO IMPUESTO_VALOR VALUES('525',1,0,NULL,'R','PAGO AL EXTERIOR - DONACIONES EN DINERO - IMPUESTO A LAS DONACIONES','2016-05-01',NULL,1,'S');
INSERT INTO IMPUESTO_VALOR VALUES('6',2,0,0,'I','NO OBJETO DE IMPUESTO','2009-07-04',NULL,6,'N');
INSERT INTO IMPUESTO_VALOR VALUES('7',2,0,0,'I','EXENTO','2014-06-30',NULL,7,'N');
INSERT INTO IMPUESTO_VALOR VALUES('8',2,12,70,'A','12%','2017-06-01',NULL,2,'N');


SELECT COUNT(*) FROM IMPUESTO_VALOR;

INSERT INTO FORMAS_PAGO VALUES('01','SIN UTILIZACION DEL SISTEMA FINANCIERO','2013-01-01',NULL);
INSERT INTO FORMAS_PAGO VALUES('02','CHEQUE PROPIO','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('03','CHEQUE CERTIFICADO','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('04','CHEQUE DE GERENCIA','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('05','CHEQUE DEL EXTERIOR','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('06','DEBITO DE CUENTA','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('07','TRANSFERENCIA PROPIO BANCO','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('08','TRANSFERENCIA OTRO BANCO NACIONAL','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('09','TRANSFERENCIA BANCO EXTERIOR','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('10','TARJETA DE CREDITO NACIONAL','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('11','TARJETA DE CREDITO INTERNACIONAL','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('12','GIRO','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('13','DEPOSITO EN CUENTA (CORRIENTE/AHORROS)','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('14','ENDOSO DE INVERSION','2013-01-01','2016-08-31');
INSERT INTO FORMAS_PAGO VALUES('15','COMPENSACION DE DEUDAS','2013-01-01',NULL);
INSERT INTO FORMAS_PAGO VALUES('16','TARJETAS DE DEBITO','2016-05-01',NULL);
INSERT INTO FORMAS_PAGO VALUES('17','DINERO ELECTRONICO','2016-05-01',NULL);
INSERT INTO FORMAS_PAGO VALUES('18','TARJETA PREPAGO','2016-05-01',NULL);
INSERT INTO FORMAS_PAGO VALUES('19','TARJETA DE CREDITO','2016-09-01',NULL);
INSERT INTO FORMAS_PAGO VALUES('20','OTROS CON UTILIZACION DEL SISTEMA FINANCIERO','2016-09-01',NULL);
INSERT INTO FORMAS_PAGO VALUES('21','ENDOSO DE TITULOS','2016-09-01',NULL);

SELECT * FROM FORMAS_PAGO;


/*
INSERT COMPENSACIONES
*/
INSERT INTO COMPENSACIONES VALUES(1,2,3,'DESCUENTO SOLIDARIO 2%','2016-06-01',NULL);
INSERT INTO COMPENSACIONES VALUES(2,4,3,'DEVOLUCION IVA 4% DINERO ELECTRONICO','2016-06-01',NULL);
INSERT INTO COMPENSACIONES VALUES(3,1,3,'DEVOLUCION IVA 1% TARJETA DEBITO O PREPAGO','2016-06-01',NULL);
INSERT INTO COMPENSACIONES VALUES(4,1,3,'DEVOLUCION IVA 1% TARJETA CREDITO','2016-06-01',NULL);
INSERT INTO COMPENSACIONES VALUES(5,2,2,'DINERO ELECTRONICO','2016-05-01',NULL);
INSERT INTO COMPENSACIONES VALUES(7,1,2,'TARJETA DEBITO O PREPAGO','2016-06-01',NULL) ;
INSERT INTO COMPENSACIONES VALUES(8,1,2,'TARJETA CREDITO','2016-06-01',NULL);

SELECT * FROM COMPENSACIONES;